// <auto-generated />
using Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Db.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20191024070739_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Db.Models.ActaPublicada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blancos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Circunscripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoMesa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Computada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Eleccion")
                        .HasColumnType("TEXT");

                    b.Property<int>("FPV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inscritos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localidad")
                        .HasColumnType("TEXT");

                    b.Property<int>("M21F")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MAS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MNR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MTS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Municipio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nulos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroDepartamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroMunicipio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PDC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pais")
                        .HasColumnType("TEXT");

                    b.Property<int>("PanBol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provincia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recinto")
                        .HasColumnType("TEXT");

                    b.Property<int>("UCS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Validos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Actas");
                });
#pragma warning restore 612, 618
        }
    }
}
